hi_msg: "Xin chÃ o! TÃ´i lÃ  Jenny Le La ğŸ¤–\n\n"

nothing_to_retry: "KhÃ´ng cÃ³ tin nháº¯n Ä‘á»ƒ thá»­ láº¡i ğŸ¤·â€â™‚ï¸"

help_message: |
  Commands:
  âšª /retry â€“ Táº¡o láº¡i cÃ¢u tráº£ lá»i cuá»‘i
  âšª /new â€“ Báº¯t Ä‘áº§u cuá»™c há»™i thoáº¡i má»›i
  âšª /mode â€“ Chá»n cháº¿ Ä‘á»™ há»— trá»£
  âšª /settings â€“ Cáº¥u hÃ¬nh
  âšª /balance â€“ Kiá»ƒm tra sá»‘ dÆ°
  âšª /help â€“ Trá»£ giÃºp

  ğŸ¨ Táº¡o áº£nh tá»« vÄƒn báº£n táº¡i <b>ğŸ‘©â€ğŸ¨ Há»a sÄ©</b> /mode
  ğŸ‘¥ ThÃªm bot vÃ o <b>Cuá»™c trÃ² chuyá»‡n nhÃ³m</b>: /help_group_chat
  ğŸ¤ Báº¡n cÃ³ thá»ƒ gá»­i <b>Tin nháº¯n thoáº¡i</b> thay vÃ¬ vÄƒn báº£n

help_group_message: |
  Báº¡n cÃ³ thá»ƒ thÃªm bot vÃ o báº¥t ká»³ <b>Cuá»™c trÃ² chuyá»‡n nhÃ³m</b> nÃ o Ä‘á»ƒ giÃºp Ä‘á»¡ vÃ  giáº£i trÃ­ cho nhá»¯ng ngÆ°á»i tham gia!

  HÆ°á»›ng dáº«n (xem <b>video</b> bÃªn dÆ°á»›i):

  1. ThÃªm bot vÃ o nhÃ³m chat
  2. Äáº·t nÃ³ lÃ m <b>quáº£n trá»‹ viÃªn</b>, Ä‘á»ƒ nÃ³ cÃ³ thá»ƒ xem tin nháº¯n (táº¥t cáº£ cÃ¡c quyá»n khÃ¡c cÃ³ thá»ƒ bá»‹ háº¡n cháº¿)
  3. ThÃ nh cÃ´ng!

  Äá»ƒ nháº­n pháº£n há»“i tá»« bot trong nhÃ³m chat â€“ @ <b>tag</b> nÃ³ hoáº·c <b>tráº£ lá»i</b> tin nháº¯n cá»§a nÃ³.
  VÃ­ dá»¥: "{bot_username} viáº¿t má»™t bÃ i thÆ¡ vá» Telegram"

subsciption_msg: |
 ğŸ‰ ÄÄƒng kÃ½ mang láº¡i cho báº¡n:
  â¤· 100,000 tokens má»—i ngÃ y (hÆ¡n 50 trang A4 vÄƒn báº£n cho ChatGPT!)
  â¤· âš¡ï¸ Tráº£ lá»i tá»©c thÃ¬
  â¤· Truy cáº­p vÃ o GPT-4
  â¤· CÃ¡c cháº¿ Ä‘á»™ trÃ² chuyá»‡n CHUYÃŠN NGHIá»†P: ğŸ‘©â€ğŸ¨ AI táº¡o áº£nh, ğŸš€ TÆ° váº¥n khá»i nghiá»‡p, ...
  â¤· ğŸ™ Nháº­n dáº¡ng tin nháº¯n thoáº¡i
  â¤· ÄÄƒng kÃ½ lÃ  lá»±a chá»n hoÃ n háº£o cho cÃ´ng viá»‡c hÃ ng ngÃ y

  Chá»n thá»i gian Ä‘Äƒng kÃ½:

balace_menu: |
  ğŸŸ£ Token Miá»…n PhÃ­ Cá»§a Báº¡n:
    â¤· Sá»‘ Token cÃ²n láº¡i: <b>{token_free}</b>

  {subcription}

  ğŸŸ£ GÃ³i Token Cá»§a Báº¡n:
    â¤· Sá»‘ Token cÃ²n láº¡i: <b>{token_pack}</b>

  Mua ÄÄƒng KÃ½ hoáº·c GÃ³i Token Ä‘á»ƒ sá»­ dá»¥ng Ä‘áº§y Ä‘á»§ chá»©c nÄƒng cá»§a bot! (nháº¥n vÃ o nÃºt bÃªn dÆ°á»›i)

  ğŸ‰ ÄÄƒng kÃ½ mang láº¡i cho báº¡n:
    â¤· 100,000 tokens má»—i ngÃ y (hÆ¡n 50 trang A4 vÄƒn báº£n cho ChatGPT!)
    â¤· âš¡ï¸ Tráº£ lá»i tá»©c thÃ¬
    â¤· Truy cáº­p vÃ o GPT-4
    â¤· CÃ¡c cháº¿ Ä‘á»™ trÃ² chuyá»‡n CHUYÃŠN NGHIá»†P: ğŸ‘©â€ğŸ¨ AI táº¡o áº£nh, ğŸš€ TÆ° váº¥n khá»i nghiá»‡p, ...
    â¤· ğŸ™ Nháº­n dáº¡ng tin nháº¯n thoáº¡i
    â¤· ÄÄƒng kÃ½ lÃ  lá»±a chá»n hoÃ n háº£o cho cÃ´ng viá»‡c hÃ ng ngÃ y

  ğŸ“¦ GÃ³i Token
    â¤· Token cÃ³ thá»ƒ Ä‘Æ°á»£c sá»­ dá»¥ng báº¥t cá»© lÃºc nÃ o
    â¤· Há»¯u Ã­ch khi báº¡n cáº§n nhiá»u token cÃ¹ng má»™t lÃºc (vÃ­ dá»¥, khi viáº¿t má»™t cuá»‘n sÃ¡ch)

subcription_none: |
  ğŸŸ£ ÄÄƒng kÃ½ cá»§a báº¡n:
    â¤· Báº¡n khÃ´ng cÃ³ Ä‘Äƒng kÃ½ nÃ o Ä‘ang hoáº¡t Ä‘á»™ng.

subcription_not_none: |
  ğŸŸ£ ÄÄƒng kÃ½ cá»§a báº¡n:
    â¤· Sá»‘ Token cÃ²n láº¡i (hÃ´m nay): <b>{token_daily}</b>
    â¤· NgÃ y káº¿t thÃºc há»£p Ä‘á»“ng: <b>{end_date}</b>