hi_msg: "Hi! I'm <b>ChatGPT</b> bot implemented with OpenAI API ğŸ¤–\n\n"

nothing_to_retry: "No message to retry ğŸ¤·â€â™‚ï¸"

help_message: |
  Commands:
  âšª /retry â€“ Regenerate last bot answer
  âšª /new â€“ Start new dialog
  âšª /mode â€“ Select chat mode
  âšª /settings â€“ Show settings
  âšª /balance â€“ Show balance
  âšª /help â€“ Show help

  ğŸ¨ Generate images from text prompts in <b>ğŸ‘©â€ğŸ¨ Artist</b> /mode
  ğŸ‘¥ Add bot to <b>group chat</b>: /help_group_chat
  ğŸ¤ You can send <b>Voice Messages</b> instead of text

help_group_message: |
  You can add bot to any <b>group chat</b> to help and entertain its participants!

  Instructions (see <b>video</b> below):
  1. Add the bot to the group chat
  2. Make it an <b>admin</b>, so that it can see messages (all other rights can be restricted)
  3. You're awesome!

  To get a reply from the bot in the chat â€“ @ <b>tag</b> it or <b>reply</b> to its message.
  For example: "{bot_username} write a poem about Telegram"

subsciption_msg: |
 ğŸ‰ Subscription gives you:
  â¤· 100,000 tokens per day (that's 50+ A4-pages of text for ChatGPT!)
  â¤· âš¡ï¸ Instant replies
  â¤· Access to GPT-4
  â¤· PRO chat modes: ğŸ‘©â€ğŸ¨ Image Generation, ğŸ’‹ Eva Elfie, ...
  â¤· ğŸ™ Voice Messages recognition
  â¤· Subscription is the perfect option for daily tasks

 Choose subscription period: