hi_msg: "Xin chÃ o! TÃ´i lÃ  Jenny Le La ğŸ¤–\n\n"

nothing_to_retry: "KhÃ´ng cÃ³ tin nháº¯n Ä‘á»ƒ thá»­ láº¡i ğŸ¤·â€â™‚ï¸"

help_message: |
  Commands:
  âšª /retry â€“ Táº¡o láº¡i cÃ¢u tráº£ lá»i cuá»‘i
  âšª /new â€“ Báº¯t Ä‘áº§u cuá»™c há»™i thoáº¡i má»›i
  âšª /mode â€“ Chá»n cháº¿ Ä‘á»™ há»— trá»£
  âšª /settings â€“ Cáº¥u hÃ¬nh
  âšª /balance â€“ Kiá»ƒm tra sá»‘ dÆ°
  âšª /help â€“ Trá»£ giÃºp

  ğŸ¨ Táº¡o áº£nh tá»« vÄƒn báº£n táº¡i <b>ğŸ‘©â€ğŸ¨ Há»a sÄ©</b> /mode
  ğŸ‘¥ ThÃªm bot vÃ o <b>Cuá»™c trÃ² chuyá»‡n nhÃ³m</b>: /help_group_chat
  ğŸ¤ Báº¡n cÃ³ thá»ƒ <b>Voice Messages</b> thay vÃ¬ vÄƒn báº£n

help_group_message: |
  Báº¡n cÃ³ thá»ƒ thÃªm bot vÃ o báº¥t ká»³ <b>Cuá»™c trÃ² chuyá»‡n nhÃ³m</b> nÃ o Ä‘á»ƒ giÃºp Ä‘á»¡ vÃ  giáº£i trÃ­ cho nhá»¯ng ngÆ°á»i tham gia!

  Instructions (see <b>video</b> below):
  1. Add the bot to the group chat
  2. Make it an <b>admin</b>, so that it can see messages (all other rights can be restricted)
  3. You're awesome!

  To get a reply from the bot in the chat â€“ @ <b>tag</b> it or <b>reply</b> to its message.
  For example: "{bot_username} write a poem about Telegram"

subsciption_msg: |
 ğŸ‰ ÄÄƒng kÃ½ mang láº¡i cho báº¡n:
  â¤· 100,000 tokens má»—i ngÃ y (hÆ¡n 50 trang A4 vÄƒn báº£n cho ChatGPT!)
  â¤· âš¡ï¸ Tráº£ lá»i tá»©c thÃ¬
  â¤· Truy cáº­p vÃ o GPT-4
  â¤· CÃ¡c cháº¿ Ä‘á»™ trÃ² chuyá»‡n CHUYÃŠN NGHIá»†P: ğŸ’‹ Eva Elfie, ...
  â¤· ğŸ™ Nháº­n dáº¡ng tin nháº¯n thoáº¡i
  â¤· ÄÄƒng kÃ½ lÃ  lá»±a chá»n hoÃ n háº£o cho cÃ´ng viá»‡c hÃ ng ngÃ y

 Chá»n thá»i gian Ä‘Äƒng kÃ½: