provider_token:
  stripe: "284685063:TEST:OTUwYjZiNjJhMjFk"

contracts:
  weekly:
    text: "ğŸ‰ Weekly | $2.49"
    contact_type: "Weekly"
    description: "GÃ³i Ä‘Äƒng kÃ½ cho báº¡n 100.000 token má»—i 24 giá». 100.000 token tÆ°Æ¡ng Ä‘Æ°Æ¡ng khoáº£ng 70 trang (A4) vÄƒn báº£n!"
    providers:
      stripe:
        title: "ğŸŒğŸ’³ Visa/Mastercard/etc - $2.49"
        price: 249
        method: "card"
        currency: "USD"

  monthly:
    text: "ğŸ‰ Monthly | $1.35 / week (â€“45%)"
    contact_type: "Monthly"
    description: "GÃ³i Ä‘Äƒng kÃ½ cho báº¡n 100.000 token má»—i 24 giá». 100.000 token tÆ°Æ¡ng Ä‘Æ°Æ¡ng khoáº£ng 70 trang (A4) vÄƒn báº£n!"
    providers:
      stripe:
        title: "ğŸŒğŸ’³ Visa/Mastercard/etc - $5.99"
        price: 599
        method: "card"
        currency: "USD"

  yearly:
    text: "ğŸ‰ Yearly | $0.96 / week (â€“60%)"
    contact_type: "Yearly"
    description: "GÃ³i Ä‘Äƒng kÃ½ cho báº¡n 100.000 token má»—i 24 giá». 100.000 token tÆ°Æ¡ng Ä‘Æ°Æ¡ng khoáº£ng 70 trang (A4) vÄƒn báº£n!"
    providers:
      stripe:
        title: "ğŸŒğŸ’³ Visa/Mastercard/etc - $49.99"
        price: 4999
        method: "card"
        currency: "USD"

packages:
  B500k:
    text: "ğŸ“¦ +500,000 Tokens | $5.99"
    description: "ğŸ“¦ +500,000 Token | $5.99 \nToken cÃ³ thá»ƒ Ä‘Æ°á»£c sá»­ dá»¥ng báº¥t cá»© lÃºc nÃ o. Há»¯u Ã­ch khi báº¡n cáº§n nhiá»u token cÃ¹ng má»™t lÃºc (vÃ­ dá»¥, khi viáº¿t sÃ¡ch)\n\nChá»n phÆ°Æ¡ng thá»©c thanh toÃ¡n:"
    token: 500000
    providers:
      stripe:
        title: "ğŸŒğŸ’³ Visa/Mastercard/etc - $5.99"
        price: 599
        method: "card"
        currency: "USD"

  B1M:
    text: "ğŸ“¦ +1,000,000 Tokens | $8.99 (-25%)"
    description: "ğŸ“¦ +1,000,000 Token | $8.99 (-25%) \nToken cÃ³ thá»ƒ Ä‘Æ°á»£c sá»­ dá»¥ng báº¥t cá»© lÃºc nÃ o. Há»¯u Ã­ch khi báº¡n cáº§n nhiá»u token cÃ¹ng má»™t lÃºc (vÃ­ dá»¥, khi viáº¿t sÃ¡ch)\n\nChá»n phÆ°Æ¡ng thá»©c thanh toÃ¡n:"
    token: 1000000
    providers:
      stripe:
        title: "ğŸŒğŸ’³ Visa/Mastercard/etc - $8.99"
        price: 899
        method: "card"
        currency: "USD"

  B3M:
    text: "ğŸ“¦ +3,000,000 Tokens | $19.99 (-45%)"
    description: "ğŸ“¦ +3,000,000 Token | $19.99 (-45%) \nToken cÃ³ thá»ƒ Ä‘Æ°á»£c sá»­ dá»¥ng báº¥t cá»© lÃºc nÃ o. Há»¯u Ã­ch khi báº¡n cáº§n nhiá»u token cÃ¹ng má»™t lÃºc (vÃ­ dá»¥, khi viáº¿t sÃ¡ch)\n\nChá»n phÆ°Æ¡ng thá»©c thanh toÃ¡n:"
    token: 3000000
    providers:
      stripe:
        title: "ğŸŒğŸ’³ Visa/Mastercard/etc - $19.99"
        price: 1999
        method: "card"
        currency: "USD"

  B10M:
    text: "ğŸ“¦ +10,000,000 Tokens | $59.99 (-50%)"
    description: "ğŸ“¦ +10,000,000 Token | $59.99 (-50%) \nToken cÃ³ thá»ƒ Ä‘Æ°á»£c sá»­ dá»¥ng báº¥t cá»© lÃºc nÃ o. Há»¯u Ã­ch khi báº¡n cáº§n nhiá»u token cÃ¹ng má»™t lÃºc (vÃ­ dá»¥, khi viáº¿t sÃ¡ch)\n\nChá»n phÆ°Æ¡ng thá»©c thanh toÃ¡n:"
    token: 10000000
    providers:
      stripe:
        title: "ğŸŒğŸ’³ Visa/Mastercard/etc - $59.99"
        price: 5999
        method: "card"
        currency: "USD"

  B50M:
    text: "ğŸ“¦ +50,000,000 Tokens | $249.99 (-60%)"
    description: "ğŸ“¦ +50,000,000 Token | $249.99 (-60%) \nToken cÃ³ thá»ƒ Ä‘Æ°á»£c sá»­ dá»¥ng báº¥t cá»© lÃºc nÃ o. Há»¯u Ã­ch khi báº¡n cáº§n nhiá»u token cÃ¹ng má»™t lÃºc (vÃ­ dá»¥, khi viáº¿t sÃ¡ch)\n\nChá»n phÆ°Æ¡ng thá»©c thanh toÃ¡n:"
    token: 50000000
    providers:
      stripe:
        title: "ğŸŒğŸ’³ Visa/Mastercard/etc - $249.99"
        price: 24999
        method: "card"
        currency: "USD"