provider_token:
  stripe: "284685063:TEST:OTUwYjZiNjJhMjFk"

contracts:
  weekly:
    text: "ğŸ‰ Weekly | $2.49"
    contact_type: "Weekly"
    description: "Subscription gives you 100,000 tokens every 24 hours. 100,000 tokens is about 70 pages (A4) of text!"
    providers:
      stripe:
        title: "ğŸŒğŸ’³ Visa/Mastercard/etc - $2.49"
        price: 249
        method: "card"
        currency: "USD"

  monthly:
    text: "ğŸ‰ Monthly | $1.35 / week (â€“45%)"
    contact_type: "Monthly"
    description: "Subscription gives you 100,000 tokens every 24 hours. 100,000 tokens is about 70 pages (A4) of text!"
    providers:
      stripe:
        title: "ğŸŒğŸ’³ Visa/Mastercard/etc - $5.99"
        price: 599
        method: "card"
        currency: "USD"

  yearly:
    text: "ğŸ‰ Yearly | $0.96 / week (â€“60%)"
    contact_type: "Yearly"
    description: "Subscription gives you 100,000 tokens every 24 hours. 100,000 tokens is about 70 pages (A4) of text!"
    providers:
      stripe:
        title: "ğŸŒğŸ’³ Visa/Mastercard/etc - $49.99"
        price: 4999
        method: "card"
        currency: "USD"

packages:
  B500k:
    text: "ğŸ“¦ +500,000 Tokens | $5.99"
    description: "ğŸ“¦ +500,000 Tokens | $5.99 \nTokens can be used at any time. Useful when you need a lot of tokens at once (for example, when writing a book)\n\nChoose a payment method:"
    token: 500000
    providers:
      stripe:
        title: "ğŸŒğŸ’³ Visa/Mastercard/etc - $5.99"
        price: 599
        method: "card"
        currency: "USD"

  B1M:
    text: "ğŸ“¦ +1,000,000 Tokens | $8.99 (-25%)"
    description: "ğŸ“¦ +1,000,000 Tokens | $8.99 (-25%)\nTokens can be used at any time. Useful when you need a lot of tokens at once (for example, when writing a book)\n\nChoose a payment method:"
    token: 1000000
    providers:
      stripe:
        title: "ğŸŒğŸ’³ Visa/Mastercard/etc - $8.99"
        price: 899
        method: "card"
        currency: "USD"

  B3M:
    text: "ğŸ“¦ +3,000,000 Tokens | $19.99 (-45%)"
    description: "ğŸ“¦ +3,000,000 Tokens | $19.99 (-45%)\nTokens can be used at any time. Useful when you need a lot of tokens at once (for example, when writing a book)\n\nChoose a payment method:"
    token: 3000000
    providers:
      stripe:
        title: "ğŸŒğŸ’³ Visa/Mastercard/etc - $19.99"
        price: 1999
        method: "card"
        currency: "USD"

  B10M:
    text: "ğŸ“¦ +10,000,000 Tokens | $59.99 (-50%)"
    description: "ğŸ“¦ +10,000,000 Tokens | $59.99 (-50%)\nTokens can be used at any time. Useful when you need a lot of tokens at once (for example, when writing a book)\n\nChoose a payment method:"
    token: 10000000
    providers:
      stripe:
        title: "ğŸŒğŸ’³ Visa/Mastercard/etc - $59.99"
        price: 5999
        method: "card"
        currency: "USD"

  B50M:
    text: "ğŸ“¦ +50,000,000 Tokens | $249.99 (-60%)"
    description: "ğŸ“¦ +50,000,000 Tokens | $249.99 (-60%)\nTokens can be used at any time. Useful when you need a lot of tokens at once (for example, when writing a book)\n\nChoose a payment method:"
    token: 50000000
    providers:
      stripe:
        title: "ğŸŒğŸ’³ Visa/Mastercard/etc - $249.99"
        price: 24999
        method: "card"
        currency: "USD"